---
title: "Weight Lifting Excercises Classification"
output:
  pdf_document:
    toc: no
  html_document:
    theme: united
    toc: no
    self_contained: true
---
Weight Lifting Excercises Classification
==========================================
## load and clean data

clean csv for fread automatic type detection

```shell
sed -e 's/\"//g' -e 's/#DIV\/0!/NA/g' pml-training.csv > 2.csv
sed -e 's/\"//g' -e 's/#DIV\/0!/NA/g' pml-testing.csv > 4.csv
```

remove variables with almost/all NAs   

```{r cache=TRUE}
library(data.table)
wle <- fread('2.csv')
testing <- fread('4.csv')
wle <- subset(wle, select=-c(1:7))
naall <- apply(wle, 2, function(x) sum(is.na(x)))
cols <- names(which(naall==0))
wle <- subset(wle, select=cols)
wle$classe <- factor(wle$classe)
```

## build model
use randomforest for classification  
use 4 folds crossvalidation for accuracy estimation
```{r cache=TRUE}
library(caret) 
library(kernlab)
tc <- trainControl(method='cv', number=4, repeats=1)
timecost <- system.time(modelFit <- train(classe~., data=wle, method='rf', trControl=tc))
timecost
modelFit
```
we can see from model output that the accuracy estimate is about 99%  
## prediction

```{r}
predictions <- predict(modelFit, newdata=testing)
predictions
```


## write to submit files
```{r results='hide'}
pml_write_files = function(x){
    n = length(x)
    for(i in 1:n){
        filename = paste0("problem_id_",i,".txt")
        write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
    }
}
pml_write_files(predictions)        
```
